def confusion_table(matrix,model):
    name = model.replace(" ", "")
    print("#set align(center)")
    print("#figure(")
    print("  table(")
    print("    columns: 3,")
    print("    align:center,")
    print("    table.header(")
    print("      [],[Fire],[Not Fire]")
    print("    ),")
    print(f"    [Fire],[{matrix[0][0]}],[{matrix[0][1]}],")
    print(f"    [Not Fire],[{matrix[1][0]}],[{matrix[1][1]}],")
    print("  ),")
    print(f"  caption: [Confusion matrix for {model}.]")
    print(f")<Table{name}Matrix>")
    print("#set align(left)" + "\n")

def classification_report_table(report, model):
    name = model.replace(" ", "")
    print("#set align(center)")
    print("#figure(")
    print("  table(")
    print("    columns: 5,")
    print("    align:center,")
    print("    table.header(")
    print("      [],[Precision],[Recall],[F1-Score],[Support]")
    print("    ),")
    print(f"    [Not Fire],[{report['Not Fire']['precision']:.2f}],[{report['Not Fire']['recall']:.2f}],[{report['Not Fire']['f1-score']:.2f}],[{report['Not Fire']['support']:.0f}],")
    print(f"    [Fire],[{report['Fire']['precision']:.2f}],[{report['Fire']['recall']:.2f}],[{report['Fire']['f1-score']:.2f}],[{report['Fire']['support']:.0f}],")
    print(f"    [accuracy],[],[],[{report['accuracy']:.2f}],[{report['Not Fire']['support']+report['Fire']['support']:.2f}],")
    print(f"    [macro avg],[{report['macro avg']['precision']:.2f}],[{report['macro avg']['recall']:.2f}],[{report['macro avg']['f1-score']:.2f}],[{report['macro avg']['support']:.0f}],")
    print(f"    [weighted avg],[{report['weighted avg']['precision']:.2f}],[{report['weighted avg']['recall']:.2f}],[{report['weighted avg']['f1-score']:.2f}],[{report['weighted avg']['support']:.0f}],")
    print("  ),")
    print(f"  caption: [Confusion matrix for {model}.]")
    print(f")<Table{name}Matrix>")
    print("#set align(left)" + "\n")